# Generated by Django 4.0.4 on 2022-06-11 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sctg_code', models.IntegerField(default=0)),
                ('description', models.CharField(default='SCTG suppressed', max_length=100)),
                ('sctg_group', models.CharField(default='0000', max_length=5)),
            ],
        ),
    ]
