# Generated by Django 4.0.4 on 2022-06-11 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naics_code', models.IntegerField(default=484)),
                ('description', models.CharField(default='Truck transportation', max_length=100)),
            ],
        ),
    ]
