# Generated by Django 4.0.4 on 2022-06-12 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_statarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statarea',
            name='csa_name',
            field=models.CharField(max_length=60),
        ),
    ]
