# Generated by Django 4.0.4 on 2022-06-15 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marketarea',
            options={'ordering': ('state',)},
        ),
    ]
