# Generated by Django 4.0.4 on 2022-06-15 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_alter_marketarea_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statarea',
            options={'ordering': ('state',)},
        ),
    ]
