# Generated by Django 4.0.4 on 2022-06-15 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_alter_statarea_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ('state',)},
        ),
    ]
