# Generated by Django 4.0.4 on 2022-06-15 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_alter_city_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ('name', 'state')},
        ),
    ]
