# Generated by Django 4.0.4 on 2022-06-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0012_metroarea_rename_center_marketarea_core_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metroarea',
            name='fips',
            field=models.IntegerField(default=36),
        ),
    ]
