# Generated by Django 4.0.4 on 2022-06-16 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0013_metroarea_fips'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='metro_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='cities', to='market.metroarea'),
        ),
    ]
