# Generated by Django 4.0.4 on 2022-04-30 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(default=0, max_length=50)),
                ('lastName', models.CharField(default=0, max_length=50)),
                ('phone', models.CharField(default=0, max_length=20)),
                ('telegram', models.CharField(default=0, max_length=20)),
                ('mc', models.CharField(blank=True, max_length=10)),
                ('usdot', models.CharField(blank=True, max_length=10)),
                ('companyName', models.CharField(blank=True, max_length=50)),
                ('entity', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True, max_length=500)),
                ('state', models.CharField(default=0, max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issueDate', models.DateTimeField()),
                ('expiryDate', models.DateTimeField()),
                ('entity', models.CharField(default=0, max_length=50)),
                ('result', models.CharField(default=0, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(default=0, max_length=50)),
                ('lastName', models.CharField(default=0, max_length=50)),
                ('phone', models.CharField(default=0, max_length=20)),
                ('telegram', models.CharField(default=0, max_length=20)),
                ('mc', models.CharField(blank=True, max_length=10)),
                ('usdot', models.CharField(blank=True, max_length=10)),
                ('cdl', models.CharField(blank=True, max_length=10)),
                ('vin', models.CharField(blank=True, max_length=10)),
                ('trailer', models.CharField(blank=True, max_length=10)),
                ('address', models.TextField(blank=True, max_length=500)),
                ('state', models.CharField(default=0, max_length=2)),
                ('gRate', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('originState', models.CharField(default=0, max_length=2)),
                ('originAddress', models.TextField(default=0, max_length=500)),
                ('originMarket', models.CharField(default=0, max_length=50)),
                ('destinationState', models.CharField(default=0, max_length=2)),
                ('destinationAddress', models.TextField(default=0, max_length=500)),
                ('destinationMarket', models.CharField(default=0, max_length=50)),
                ('pickupDate', models.DateTimeField()),
                ('deliveryDate', models.DateTimeField()),
                ('mileage', models.SmallIntegerField(default=0)),
                ('deadhead', models.SmallIntegerField(default=0)),
                ('gross', models.FloatField(default=0)),
                ('fuelBurnt', models.FloatField(default=0)),
                ('fuelPrice', models.FloatField(default=0)),
                ('toll', models.FloatField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='orders', to='dash.customer')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='orders', to='dash.driver')),
            ],
        ),
    ]
