# Generated by Django 4.0.4 on 2022-05-02 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='birthDate',
            field=models.DateField(null=True),
        ),
    ]
