# Generated by Django 4.0.4 on 2022-05-02 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0002_driver_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='birthDate',
            field=models.DateField(blank=True, default='2022-02-01', null=True),
        ),
    ]
