# Generated by Django 4.0.4 on 2022-05-09 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0002_alter_order_broker_alter_order_shipper'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trailer',
            old_name='owner',
            new_name='ownership',
        ),
        migrations.RenameField(
            model_name='truck',
            old_name='owner',
            new_name='ownership',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='cdl',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='cdl_expiry',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='trailer',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='trailer_type',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='vin',
        ),
        migrations.AddField(
            model_name='order',
            name='temperature',
            field=models.FloatField(blank=True, default=70),
        ),
        migrations.AddField(
            model_name='order',
            name='trailer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='dash.trailer'),
        ),
        migrations.AddField(
            model_name='order',
            name='truck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='dash.truck'),
        ),
    ]
