# Generated by Django 4.0.4 on 2022-05-09 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0003_rename_owner_trailer_ownership_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdocument',
            name='name',
            field=models.CharField(choices=[('BOL', 'Bill of Lading'), ('INV', 'Invoice'), ('RCON', 'Rate Confirmation')], default='BOL', max_length=10),
        ),
    ]
