# Generated by Django 4.0.4 on 2022-05-03 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0004_alter_driver_phone_alter_driver_telegram'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='zipCode',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='driver',
            name='zipCode',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='destinationZipCode',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='originZipCode',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='customer',
            name='firstName',
            field=models.CharField(default='Scott', max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='lastName',
            field=models.CharField(default='Pilgrim', max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, default='1(xxx)xxx-xx-xx', max_length=25),
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(default='NY', max_length=2),
        ),
        migrations.AlterField(
            model_name='customer',
            name='telegram',
            field=models.CharField(blank=True, default='durov', max_length=20),
        ),
        migrations.AlterField(
            model_name='driver',
            name='address',
            field=models.TextField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='driver',
            name='firstName',
            field=models.CharField(default='Scott', max_length=20),
        ),
        migrations.AlterField(
            model_name='driver',
            name='lastName',
            field=models.CharField(default='Pilgrim', max_length=20),
        ),
        migrations.AlterField(
            model_name='driver',
            name='phone',
            field=models.CharField(blank=True, default='1(xxx)xxx-xx-xx', max_length=25),
        ),
        migrations.AlterField(
            model_name='driver',
            name='state',
            field=models.CharField(default='NY', max_length=2),
        ),
        migrations.AlterField(
            model_name='driver',
            name='telegram',
            field=models.CharField(blank=True, default='durov', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='destinationAddress',
            field=models.TextField(default=0, max_length=70),
        ),
        migrations.AlterField(
            model_name='order',
            name='destinationState',
            field=models.CharField(default='NY', max_length=2),
        ),
        migrations.AlterField(
            model_name='order',
            name='originAddress',
            field=models.TextField(default=0, max_length=70),
        ),
        migrations.AlterField(
            model_name='order',
            name='originState',
            field=models.CharField(default='NY', max_length=2),
        ),
    ]
