# Generated by Django 4.0.4 on 2022-05-03 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0005_customer_zipcode_driver_zipcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='gRate',
            field=models.FloatField(default=0),
        ),
    ]
