# Generated by Django 4.0.4 on 2022-05-09 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0005_alter_broker_state_alter_driver_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=10),
        ),
    ]
