# Generated by Django 4.0.4 on 2022-05-03 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0006_order_grate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='customer',
            name='telegram',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='driver',
            name='address',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='driver',
            name='birthDate',
            field=models.DateField(blank=True, default='1990-3-15', null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='phone',
            field=models.CharField(blank=True, default='+1', max_length=25),
        ),
        migrations.AlterField(
            model_name='driver',
            name='telegram',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='deliveryDate',
            field=models.DateTimeField(default='2022-01-13 08:00AM'),
        ),
        migrations.AlterField(
            model_name='order',
            name='destinationAddress',
            field=models.CharField(default=0, max_length=70),
        ),
        migrations.AlterField(
            model_name='order',
            name='originAddress',
            field=models.CharField(default=0, max_length=70),
        ),
        migrations.AlterField(
            model_name='order',
            name='pickupDate',
            field=models.DateTimeField(default='2022-01-13 08:00AM'),
        ),
    ]
