# Generated by Django 4.0.4 on 2022-05-04 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0008_order_origincity_alter_order_destinationstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='destinationCity',
            field=models.CharField(default='Palo Alto', max_length=30),
        ),
    ]
