# Generated by Django 4.0.4 on 2022-05-04 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0009_order_destinationcity'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='city',
            field=models.CharField(default='Palo Alto', max_length=30),
        ),
        migrations.AlterField(
            model_name='driver',
            name='state',
            field=models.CharField(default='CA', max_length=2),
        ),
    ]
