# Generated by Django 4.0.4 on 2022-05-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0011_customer_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(default='New York', max_length=30),
        ),
    ]
