# Generated by Django 4.0.4 on 2022-05-11 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0012_rename_name_brokerdocument_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trailer',
            name='model',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='truck',
            name='model',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
