# Generated by Django 4.0.4 on 2022-05-05 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0012_alter_customer_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paymentDue',
            field=models.DateField(default='2022-01-13'),
        ),
    ]
