# Generated by Django 4.0.4 on 2022-05-11 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0013_alter_trailer_model_alter_truck_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trailer',
            name='model',
            field=models.CharField(blank=True, default='Kamaz', max_length=50),
        ),
        migrations.AlterField(
            model_name='truck',
            name='model',
            field=models.CharField(blank=True, default='Kamaz', max_length=50),
        ),
    ]
