# Generated by Django 4.0.4 on 2022-05-11 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0014_alter_trailer_model_alter_truck_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brokerdocument',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='driverdocument',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='orderdocument',
            old_name='title',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='trailer',
            name='model',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='truck',
            name='model',
            field=models.CharField(default='', max_length=50),
        ),
    ]
