# Generated by Django 4.0.4 on 2022-05-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0015_rename_title_brokerdocument_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trailer',
            name='driver',
            field=models.ManyToManyField(blank=True, related_name='trailers', to='dash.driver'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='driver',
            field=models.ManyToManyField(blank=True, related_name='trucks', to='dash.driver'),
        ),
    ]
