# Generated by Django 4.0.4 on 2022-05-11 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0016_alter_trailer_driver_alter_truck_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trailer',
            name='model',
            field=models.CharField(default='Tesla', max_length=50),
        ),
        migrations.AlterField(
            model_name='truck',
            name='model',
            field=models.CharField(default='Tesla', max_length=50),
        ),
    ]
