# Generated by Django 4.0.4 on 2022-05-11 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0017_alter_trailer_model_alter_truck_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='trailer',
            name='height',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='trailer',
            name='length',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='trailer',
            name='weight',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='trailer',
            name='width',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='category',
            field=models.CharField(choices=[('RFR', 'Reefer'), ('VAN', 'Dry Van'), ('FLT', 'Flatbed')], default='VAN', max_length=5),
        ),
    ]
