# Generated by Django 4.0.4 on 2022-05-12 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0022_alter_order_delivery_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownership', models.CharField(choices=[('FRM', 'Company'), ('OO', 'Owner Operator')], default='OO', max_length=10)),
                ('category', models.CharField(choices=[('RFR', 'Reefer'), ('VAN', 'Dry Van'), ('FLT', 'Flatbed'), ('TRK', 'Truck')], default='VAN', max_length=5)),
                ('vin', models.CharField(blank=True, max_length=10)),
                ('model', models.CharField(default='', max_length=50)),
                ('year', models.IntegerField(blank=True)),
                ('license_plate', models.CharField(blank=True, max_length=10)),
                ('license_expiry', models.DateField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, default=0)),
                ('width', models.FloatField(blank=True, default=0)),
                ('height', models.FloatField(blank=True, default=0)),
                ('length', models.FloatField(blank=True, default=0)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='truck',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='order',
            name='trailer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='truck',
        ),
        migrations.DeleteModel(
            name='Trailer',
        ),
        migrations.DeleteModel(
            name='Truck',
        ),
        migrations.AddField(
            model_name='driver',
            name='equipment',
            field=models.ManyToManyField(blank=True, related_name='drivers', to='dash.equipment'),
        ),
        migrations.AddField(
            model_name='order',
            name='equipment',
            field=models.ManyToManyField(blank=True, null=True, related_name='orders', to='dash.equipment'),
        ),
    ]
