# Generated by Django 4.0.4 on 2022-05-12 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0023_equipment_remove_truck_driver_remove_order_trailer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='equipment',
            field=models.ManyToManyField(blank=True, related_name='orders', to='dash.equipment'),
        ),
    ]
