# Generated by Django 4.0.4 on 2022-05-13 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0024_alter_order_equipment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('CDL', "Commercial Driver's License"), ('DSP', 'Dispatcher Agreement'), ('MED', 'Medical Card'), ('DRG', 'Drug Test'), ('BOL', 'Bill of Lading'), ('INV', 'Invoice'), ('RCON', 'Rate Confirmation'), ('STP', 'Setup document')], default='RCON', max_length=10)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('issued_by', models.CharField(blank=True, max_length=50)),
                ('number', models.CharField(blank=True, max_length=20)),
                ('detail', models.CharField(blank=True, default=0, max_length=50)),
                ('broker', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, related_name='documents', to='dash.broker')),
                ('driver', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, related_name='documents', to='dash.driver')),
                ('order', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, related_name='documents', to='dash.order')),
            ],
        ),
        migrations.RemoveField(
            model_name='driverdocument',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='orderdocument',
            name='order',
        ),
        migrations.DeleteModel(
            name='BrokerDocument',
        ),
        migrations.DeleteModel(
            name='DriverDocument',
        ),
        migrations.DeleteModel(
            name='OrderDocument',
        ),
    ]
