# Generated by Django 4.0.4 on 2022-05-13 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0025_document_remove_driverdocument_driver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='broker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='documents', to='dash.broker'),
        ),
        migrations.AlterField(
            model_name='document',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='documents', to='dash.driver'),
        ),
        migrations.AlterField(
            model_name='document',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='documents', to='dash.order'),
        ),
    ]
