# Generated by Django 4.0.4 on 2022-05-13 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0027_alter_equipment_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='equipment',
        ),
        migrations.AddField(
            model_name='order',
            name='trailer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='trailer_orders', to='dash.equipment'),
        ),
        migrations.AddField(
            model_name='order',
            name='truck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='truck_orders', to='dash.equipment'),
        ),
    ]
