# Generated by Django 4.0.4 on 2022-05-14 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0028_remove_order_equipment_order_trailer_order_truck'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='equipment',
        ),
        migrations.AddField(
            model_name='equipment',
            name='owner',
            field=models.CharField(default='Gamma Trucking LLC', max_length=40),
        ),
    ]
