# Generated by Django 4.0.4 on 2022-05-14 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0029_remove_driver_equipment_equipment_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars'),
        ),
        migrations.AddField(
            model_name='driver',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars'),
        ),
        migrations.AddField(
            model_name='shipper',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars'),
        ),
    ]
