# Generated by Django 4.0.4 on 2022-05-14 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0030_broker_avatar_driver_avatar_shipper_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broker',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='shipper',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
