# Generated by Django 4.0.4 on 2022-05-18 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0031_alter_broker_avatar_alter_driver_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='scanned_copy',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
