# Generated by Django 4.0.4 on 2022-05-22 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0032_document_scanned_copy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='fuel_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='order',
            name='gross',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
