# Generated by Django 4.0.4 on 2022-06-11 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0033_alter_order_fuel_price_alter_order_gross'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='commodity',
            field=models.CharField(blank=True, default='', max_length=40, null=True),
        ),
    ]
