# Generated by Django 4.0.4 on 2022-06-11 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
        ('dash', '0035_alter_order_commodity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='commodity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='orders', to='market.commodity'),
        ),
    ]
