# Generated by Django 4.0.4 on 2022-06-11 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0037_alter_order_commodity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='broker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='orders', to='dash.broker'),
        ),
    ]
