# Generated by Django 4.0.4 on 2022-06-11 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_marketarea'),
        ('dash', '0038_alter_order_broker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='destination_market',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='orders_to', to='market.marketarea'),
        ),
        migrations.AlterField(
            model_name='order',
            name='origin_market',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='orders_from', to='market.marketarea'),
        ),
    ]
