# Generated by Django 4.0.4 on 2022-06-14 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_city'),
        ('dash', '0041_remove_order_destination_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='destination_city',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, related_name='orders_to', to='market.city'),
        ),
        migrations.AlterField(
            model_name='order',
            name='origin_city',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, related_name='orders_from', to='market.city'),
        ),
    ]
