# Generated by Django 4.0.4 on 2022-06-16 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0014_city_metro_area'),
        ('dash', '0043_remove_order_destination_market_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipper',
            name='industry',
            field=models.ForeignKey(default=23, on_delete=django.db.models.deletion.RESTRICT, related_name='shippers', to='market.industry'),
        ),
    ]
